// BELOW I USED A RUBY GEM CALLED 'NOKOGIRI' TO SCRAPE THIS WIKI PAGE => 
// DETAILED METHODS AND NOTES UNDER THE SEED INFO

var airportsByCity = {
 "Birmingham": "Birmingham–Shuttlesworth International Airport (BHM)",
 "Dothan": "Dothan Regional Airport (DHN)",
 "Huntsville": "Huntsville International Airport (Carl T. Jones Field) (HSV)",
 "Mobile": "Mobile Regional Airport (MOB)",
 "Montgomery": "Montgomery Regional Airport (MGM)",
 "Bullhead City": "Laughlin/Bullhead International Airport (IFP)",
 "Flagstaff": "Flagstaff Pulliam Airport (FLG)",
 "Grand Canyon / Tusayan": "Grand Canyon National Park Airport (GCN)",
 "Mesa": "Phoenix–Mesa Gateway Airport (IWA)",
 "Page": "Page Municipal Airport (PGA)",
 "Peach Springs": "Grand Canyon West Airport (1G4)",
 "Phoenix": "Phoenix Sky Harbor International Airport (PHX)",
 "Tucson": "Tucson International Airport (TUS)",
 "Yuma": "Yuma International Airport / MCAS Yuma (NYL)",
 "Fayetteville": "Fayetteville Regional Airport (Grannis Field) (FAY)",
 "Fort Smith": "Fort Smith Regional Airport (FSM)",
 "Little Rock": "Bill and Hillary Clinton National Airport (LIT)",
 "Texarkana": "Texarkana Regional Airport (Webb Field) (TXK)",
 "Arcata / Eureka": "Arcata Airport (ACV)",
 "Bakersfield": "Meadows Field (BFL)",
 "Burbank": "Bob Hope Airport (BUR)",
 "Carlsbad": "McClellan–Palomar Airport (CRQ)",
 "Chico": "Chico Municipal Airport (CIC)",
 "Crescent City": "Del Norte County Airport (CEC)",
 "Fresno": "Fresno Yosemite International Airport (FAT)",
 "Long Beach": "Long Beach Airport (Daugherty Field) (LGB)",
 "Los Angeles": "Los Angeles International Airport (LAX)",
 "Mammoth Lakes": "Mammoth Yosemite Airport (MMH)",
 "Modesto": "Modesto City–County Airport  (MOD)",
 "Monterey": "Monterey Regional Airport (MRY)",
 "Oakland": "Oakland International Airport (OAK)",
 "Ontario": "Ontario International Airport (ONT)",
 "Palm Springs": "Palm Springs International Airport (PSP)",
 "Redding": "Redding Municipal Airport (RDD)",
 "Sacramento": "Sacramento International Airport (SMF)",
 "San Diego": "San Diego International Airport (SAN)",
 "San Francisco": "San Francisco International Airport (SFO)",
 "San Jose": "San José International Airport (SJC)",
 "San Luis Obispo": "San Luis Obispo County Regional Airport (SBP)",
 "Santa Ana": "John Wayne Airport  (SNA)",
 "Santa Barbara": "Santa Barbara Municipal Airport (SBA)",
 "Santa Maria": "Santa Maria Public Airport  (SMX)",
 "Santa Rosa": "Charles M. Schulz–Sonoma County Airport (STS)",
 "Stockton": "Stockton Metropolitan Airport (SCK)",
 "Aspen": "Aspen-Pitkin County Airport (ASE)",
 "Colorado Springs": "City of Colorado Springs Municipal Airport (COS)",
 "Denver": "Denver International Airport (DEN)",
 "Durango": "Durango-La Plata County Airport (DRO)",
 "Eagle": "Eagle County Regional Airport (EGE)",
 "Grand Junction": "Grand Junction Regional Airport (Walker Field) (GJT)",
 "Gunnison": "Gunnison-Crested Butte Regional Airport (GUC)",
 "Hayden": "Yampa Valley Airport  (HDN)",
 "Montrose": "Montrose Regional Airport (MTJ)",
 "Hartford": "Bradley International Airport (BDL)",
 "New Haven": "Tweed New Haven Regional Airport (HVN)",
 "Daytona Beach": "Daytona Beach International Airport (DAB)",
 "Fort Lauderdale": "Fort Lauderdale–Hollywood International Airport (FLL)",
 "Fort Myers": "Southwest Florida International Airport (RSW)",
 "Gainesville": "Gainesville Regional Airport (GNV)",
 "Jacksonville": "Albert J. Ellis Airport (OAJ)",
 "Key West": "Key West International Airport (EYW)",
 "Melbourne": "Melbourne International Airport (MLB)",
 "Miami": "Miami International Airport (MIA)",
 "Orlando": "Orlando International Airport (MCO)",
 "Orlando/Sanford": "Orlando Sanford International Airport (SFB)",
 "Panama City Beach": "Northwest Florida Beaches International Airport [nb 2] (ECP)",
 "Pensacola": "Pensacola International Airport (PNS)",
 "Punta Gorda": "Punta Gorda Airport (PGD)",
 "Sarasota / Bradenton": "Sarasota–Bradenton International Airport (SRQ)",
 "St. Augustine": "Northeast Florida Regional Airport  (SGJ)",
 "St. Petersburg/Clearwater": "St. Pete–Clearwater International Airport (PIE)",
 "Tallahassee": "Tallahassee International Airport (TLH)",
 "Tampa": "Tampa International Airport (TPA)",
 "Valparaiso": "Destin–Fort Walton Beach Airport / Eglin Air Force Base (VPS)",
 "West Palm Beach": "Palm Beach International Airport (PBI)",
 "Albany": "Albany International Airport (ALB)",
 "Atlanta": "Hartsfield-Jackson Atlanta International Airport (ATL)",
 "Augusta": "Augusta Regional Airport (Bush Field) (AGS)",
 "Brunswick": "Brunswick Golden Isles Airport (BQK)",
 "Columbus": "Rickenbacker International Airport (LCK)",
 "Savannah": "Savannah/Hilton Head International Airport (SAV)",
 "Valdosta": "Valdosta Regional Airport (VLD)",
 "Hilo": "Hilo International Airport (ITO)",
 "Honolulu": "Honolulu International Airport (HNL)",
 "Kahului": "Kahului Airport (OGG)",
 "Kailua/Kona": "Kona International Airport at Keahole (KOA)",
 "Kaunakakai": "Molokai Airport (Molokaʻi Airport) (MKK)",
 "Lanai City": "Lanai Airport (Lānaʻi Airport) (LNY)",
 "Lihue": "Lihue Airport (Līhuʻe Airport) (LIH)",
 "Boise": "Boise Airport (Boise Air Terminal) (Gowen Field) (BOI)",
 "Hailey": "Friedman Memorial Airport (SUN)",
 "Idaho Falls": "Idaho Falls Regional Airport (Fanning Field) (IDA)",
 "Lewiston": "Lewiston-Nez Perce County Airport (LWS)",
 "Pocatello": "Pocatello Regional Airport (PIH)",
 "Twin Falls": "Magic Valley Regional Airport (Joslin Field) (TWF)",
 "Belleville": "MidAmerica St. Louis Airport / Scott Air Force Base (BLV)",
 "Bloomington": "Central Illinois Regional Airport at Bloomington-Normal (BMI)",
 "Champaign": "University of Illinois - Willard Airport (CMI)",
 "Chicago": "Chicago Midway International Airport (MDW)",
 "Marion": "Williamson County Regional Airport (MWA)",
 "Moline": "Quad City International Airport (MLI)",
 "Peoria": "General Downing - Peoria International Airport (PIA)",
 "Quincy": "Quincy Regional Airport (Baldwin Field) (UIN)",
 "Rockford": "Chicago Rockford International Airport (RFD)",
 "Springfield": "Springfield-Branson National Airport (SGF)",
 "Evansville": "Evansville Regional Airport (EVV)",
 "Fort Wayne": "Fort Wayne International Airport (FWA)",
 "Indianapolis": "Indianapolis International Airport (IND)",
 "South Bend": "South Bend International Airport (SBN)",
 "Cedar Rapids": "The Eastern Iowa Airport (CID)",
 "Des Moines": "Des Moines International Airport (DSM)",
 "Dubuque": "Dubuque Regional Airport (DBQ)",
 "Sioux City": "Sioux Gateway Airport (SUX)",
 "Waterloo": "Waterloo Regional Airport (ALO)",
 "Garden City": "Garden City Regional Airport (GCK)",
 "Manhattan": "Manhattan Regional Airport (MHK)",
 "Wichita": "Wichita Dwight D. Eisenhower National Airport (ICT)",
 "Covington": "Cincinnati/Northern Kentucky International Airport (CVG)",
 "Lexington": "Blue Grass Airport (LEX)",
 "Louisville": "Louisville International Airport (Standiford Field) (SDF)",
 "Owensboro": "Owensboro-Daviess County Regional Airport (OWB)",
 "Paducah": "Barkley Regional Airport (PAH)",
 "Alexandria": "Alexandria International Airport (AEX)",
 "Baton Rouge": "Baton Rouge Metropolitan Airport (Ryan Field) (BTR)",
 "Lafayette": "Lafayette Regional Airport (LFT)",
 "Lake Charles": "Lake Charles Regional Airport (LCH)",
 "Monroe": "Monroe Regional Airport (MLU)",
 "New Orleans": "Louis Armstrong New Orleans International Airport (MSY)",
 "Shreveport": "Shreveport Regional Airport (SHV)",
 "Bangor": "Bangor International Airport (BGR)",
 "Bar Harbor": "Hancock County-Bar Harbor Airport (BHB)",
 "Portland": "Portland International Airport (PDX)",
 "Rockland": "Knox County Regional Airport (RKD)",
 "Baltimore": "Baltimore/Washington International Thurgood Marshall Airport (BWI)",
 "Salisbury": "Salisbury-Ocean City Wicomico Regional Airport (SBY)",
 "Hagerstown": "Hagerstown Regional Airport (Richard A. Henson Field) (HGR)",
 "Boston": "Gen. Edward Lawrence Logan International Airport (BOS)",
 "Hyannis": "Barnstable Municipal Airport (Boardman/Polando Field) (HYA)",
 "Nantucket": "Nantucket Memorial Airport (ACK)",
 "Provincetown": "Provincetown Municipal Airport (PVC)",
 "Vineyard Haven": "Marthas Vineyard Airport (MVY)",
 "Worcester": "Worcester Regional Airport (ORH)",
 "Alpena": "Alpena County Regional Airport (APN)",
 "Charlevoix": "Charlevoix Municipal Airport (CVX)",
 "Detroit / Romulus": "Detroit Metropolitan Wayne County Airport (DTW)",
 "Escanaba": "Delta County Airport (ESC)",
 "Flint": "Bishop International Airport (FNT)",
 "Grand Rapids": "Gerald R. Ford International Airport (GRR)",
 "Hancock / Calumet": "Houghton County Memorial Airport (CMX)",
 "Iron Mountain / Kingsford": "Ford Airport (IMT)",
 "Kalamazoo / Battle Creek": "Kalamazoo/Battle Creek International Airport (AZO)",
 "Lansing": "Capital Region International Airport (LAN)",
 "Marquette / Gwinn": "Sawyer International Airport (SAW)",
 "Muskegon": "Muskegon County Airport (MKG)",
 "Pellston": "Pellston Regional Airport of Emmet County (PLN)",
 "Saginaw": "MBS International Airport (MBS)",
 "Sault Ste. Marie": "Chippewa County International Airport (CIU)",
 "Traverse City": "Cherry Capital Airport (TVC)",
 "Bemidji": "Bemidji Regional Airport (BJI)",
 "Brainerd": "Brainerd Lakes Regional Airport (BRD)",
 "Duluth": "Duluth International Airport (DLH)",
 "Hibbing": "Range Regional Airport  (HIB)",
 "International Falls": "Falls International Airport (INL)",
 "Minneapolis": "Minneapolis–St. Paul International Airport (Wold–Chamberlain Field) (MSP)",
 "Rochester": "Greater Rochester International Airport (ROC)",
 "St. Cloud": "St. Cloud Regional Airport (STC)",
 "Columbus / West Point / Starkville": "Golden Triangle Regional Airport (GTR)",
 "Gulfport / Biloxi": "Gulfport–Biloxi International Airport (GPT)",
 "Hattiesburg / Laurel": "Hattiesburg–Laurel Regional Airport (PIB)",
 "Jackson": "Jackson Hole Airport (JAC)",
 "Columbia": "Columbia Metropolitan Airport (CAE)",
 "Joplin": "Joplin Regional Airport (JLN)",
 "Kansas City": "Kansas City International Airport (originally Mid-Contintent International Airport) (MCI)",
 "St. Louis": "Lambert-St. Louis International Airport (STL)",
 "Billings": "Billings Logan International Airport (BIL)",
 "Bozeman": "Bozeman Yellowstone International Airport (BZN)",
 "Butte": "Bert Mooney Airport (BTM)",
 "Great Falls": "Great Falls International Airport (GTF)",
 "Helena": "Helena Regional Airport (HLN)",
 "Kalispell": "Glacier Park International Airport (GPI)",
 "Missoula": "Missoula International Airport (MSO)",
 "Grand Island": "Central Nebraska Regional Airport (GRI)",
 "Kearney": "Kearney Regional Airport (EAR)",
 "Lincoln": "Lincoln Airport (LNK)",
 "Omaha": "Eppley Airfield (OMA)",
 "Scottsbluff": "Western Nebraska Regional Airport (William B. Heilig Field) (BFF)",
 "Boulder City": "Boulder City Municipal Airport (BVU)",
 "Elko": "Elko Regional Airport (J.C. Harris Field) (EKO)",
 "Las Vegas": "McCarran International Airport (LAS)",
 "Reno": "Reno/Tahoe International Airport (RNO)",
 "Lebanon": "Lebanon Municipal Airport (LEB)",
 "Manchester": "Manchester–Boston Regional Airport (MHT)",
 "Atlantic City": "Atlantic City International Airport (ACY)",
 "Trenton": "Trenton Mercer Airport (TTN)",
 "Newark": "Newark Liberty International Airport (EWR)",
 "Albuquerque": "Albuquerque International Sunport (ABQ)",
 "Farmington": "Four Corners Regional Airport (FMN)",
 "Hobbs": "Lea County Regional Airport (HOB)",
 "Roswell": "Roswell International Air Center (ROW)",
 "Santa Fe": "Santa Fe Municipal Airport (SAF)",
 "Binghamton": "Greater Binghamton Airport (Edwin A. Link Field) (BGM)",
 "Buffalo": "Buffalo Niagara International Airport (BUF)",
 "Elmira / Corning": "Elmira/Corning Regional Airport (ELM)",
 "Islip": "Long Island MacArthur Airport (ISP)",
 "Ithaca": "Ithaca Tompkins Regional Airport (ITH)",
 "New York": "LaGuardia Airport (LGA)",
 "Newburgh": "Stewart International Airport (SWF)",
 "Niagara Falls": "Niagara Falls International Airport (IAG)",
 "Plattsburgh": "Plattsburgh International Airport (PBG)",
 "Syracuse": "Syracuse Hancock International Airport (SYR)",
 "Watertown": "Watertown International Airport (ART)",
 "White Plains": "Westchester County Airport (HPN)",
 "Asheville": "Asheville Regional Airport (AVL)",
 "Charlotte": "Charlotte/Douglas International Airport (CLT)",
 "Greensboro": "Piedmont Triad International Airport (GSO)",
 "Greenville": "Pitt-Greenville Airport (PGV)",
 "New Bern": "Coastal Carolina Regional Airport (EWN)",
 "Raleigh": "Raleigh-Durham International Airport (RDU)",
 "Wilmington": "Wilmington International Airport (ILM)",
 "Bismarck": "Bismarck Municipal Airport (BIS)",
 "Dickinson": "Dickinson Theodore Roosevelt Regional Airport (DIK)",
 "Fargo": "Hector International Airport (FAR)",
 "Grand Forks": "Grand Forks International Airport (GFK)",
 "Minot": "Minot International Airport (MOT)",
 "Williston": "Sloulin Field International Airport (ISN)",
 "Akron / Canton": "Akron-Canton Regional Airport (CAK)",
 "Cleveland": "Cleveland-Hopkins International Airport (CLE)",
 "Dayton": "James M. Cox Dayton International Airport (DAY)",
 "Toledo": "Toledo Express Airport (TOL)",
 "Youngstown / Warren": "Youngstown-Warren Regional Airport / Youngstown ARS (YNG)",
 "Lawton": "Lawton–Fort Sill Regional Airport (LAW)",
 "Oklahoma City": "Will Rogers World Airport (OKC)",
 "Tulsa": "Tulsa International Airport (TUL)",
 "Eugene": "Eugene Airport (Mahlon Sweet Field) (EUG)",
 "Klamath Falls": "Klamath Falls Airport (Kingsley Field) (LMT)",
 "Medford": "Rogue Valley International-Medford Airport (MFR)",
 "North Bend": "Southwest Oregon Regional Airport",
 "Redmond": "Redmond Municipal Airport (Roberts Field) (RDM)",
 "Allentown": "Lehigh Valley International Airport (ABE)",
 "Erie": "Erie International Airport (Tom Ridge Field) (ERI)",
 "Harrisburg / Middletown": "Harrisburg International Airport (MDT)",
 "Latrobe": "Arnold Palmer Regional Airport (LBE)",
 "Philadelphia": "Philadelphia International Airport (PHL)",
 "Pittsburgh": "Pittsburgh International Airport (PIT)",
 "State College": "University Park Airport (UNV)",
 "Wilkes-Barre / Scranton": "Wilkes-Barre/Scranton International Airport (AVP)",
 "Williamsport": "Williamsport Regional Airport (IPT)",
 "Providence / Warwick": "Theodore Francis Green State Airport (PVD)",
 "Westerly": "Westerly State Airport (WST)",
 "Charleston": "Yeager Airport (CRW)",
 "Florence": "Florence Regional Airport (FLO)",
 "Greer": "Greenville-Spartanburg International Airport (Roger Milliken Field) (GSP)",
 "Hilton Head Island": "Hilton Head Airport (HXD)",
 "Myrtle Beach": "Myrtle Beach International Airport (MYR)",
 "Aberdeen": "Aberdeen Regional Airport (ABR)",
 "Pierre": "Pierre Regional Airport (PIR)",
 "Rapid City": "Rapid City Regional Airport (RAP)",
 "Sioux Falls": "Sioux Falls Regional Airport (Joe Foss Field) (FSD)",
 "Bristol / Johnson City / Kingsport": "Tri-Cities Regional Airport (Tri-Cities Regional TN/VA) (TRI)",
 "Chattanooga": "Chattanooga Metropolitan Airport (Lovell Field) (CHA)",
 "Knoxville": "McGhee Tyson Airport (TYS)",
 "Memphis": "Memphis International Airport (MEM)",
 "Nashville": "Nashville International Airport (BNA)",
 "Abilene": "Abilene Regional Airport (ABI)",
 "Amarillo": "Rick Husband Amarillo International Airport (AMA)",
 "Austin": "Austin-Bergstrom International Airport (AUS)",
 "Beaumont / Port Arthur": "Jack Brooks Regional Airport (BPT)",
 "Brownsville": "Brownsville/South Padre Island International Airport (BRO)",
 "College Station": "Easterwood Airport (Easterwood Field) (CLL)",
 "Corpus Christi / Kingsville": "Corpus Christi International Airport (CRP)",
 "Dallas": "Dallas Love Field (DAL)",
 "Dallas-Fort Worth": "Dallas/Fort Worth International Airport (DFW)",
 "Del Rio": "Del Rio International Airport (DRT)",
 "El Paso": "El Paso International Airport (ELP)",
 "Fort Hood / Killeen / Temple": "Killeen-Fort Hood Regional Airport / Robert Gray Army Airfield (GRK)",
 "Harlingen": "Valley International Airport (HRL)",
 "Houston": "William P. Hobby Airport (HOU)",
 "Laredo": "Laredo International Airport (LRD)",
 "Longview": "East Texas Regional Airport (GGG)",
 "Lubbock": "Lubbock Preston Smith International Airport (LBB)",
 "Midland": "Midland International Airport (MAF)",
 "San Angelo": "San Angelo Regional Airport (Mathis Field) (SJT)",
 "San Antonio": "San Antonio International Airport (SAT)",
 "Tyler": "Tyler Pounds Regional Airport (TYR)",
 "Waco": "Waco Regional Airport (ACT)",
 "Wichita Falls": "Wichita Falls Municipal Airport / Sheppard Air Force Base (SPS)",
 "Provo": "Provo Municipal Airport (PVU)",
 "Salt Lake City": "Salt Lake City International Airport (SLC)",
 "St. George / Beaver": "St. George Regional Airport (opened 2011) (SGU)",
 "Wendover": "Wendover Airport (charter flights) (ENV)",
 "Burlington": "Burlington International Airport (BTV)",
 "Charlottesville": "Charlottesville–Albemarle Airport (CHO)",
 "Lynchburg": "Lynchburg Regional Airport (Preston Glenn Field) (LYH)",
 "Newport News": "Newport News/Williamsburg International Airport (PHF)",
 "Norfolk": "Norfolk International Airport (ORF)",
 "Richmond": "Richmond International Airport (Byrd Field) (RIC)",
 "Roanoke": "Roanoke Regional Airport (Woodrum Field) (ROA)",
 "Staunton / Waynesboro / Harrisonburg": "Shenandoah Valley Regional Airport (SHD)",
 "Washington, D.C. / Arlington County": "Ronald Reagan Washington National Airport (DCA)",
 "Washington, D.C. / Dulles / Chantilly": "Washington Dulles International Airport (IAD)",
 "Bellingham": "Bellingham International Airport (BLI)",
 "Friday Harbor": "Friday Harbor Airport (FHR)",
 "Pasco": "Tri-Cities Airport (PSC)",
 "Port Angeles": "William R. Fairchild International Airport (CLM)",
 "Pullman / Moscow, Idaho": "Pullman/Moscow Regional Airport (PUW)",
 "Seattle": "King County International Airport (Boeing Field) (BFI)",
 "Seattle / Tacoma (SeaTac)": "Seattle–Tacoma International Airport (SEA)",
 "Spokane": "Spokane International Airport (Geiger Field) (GEG)",
 "Walla Walla": "Walla Walla Regional Airport (ALW)",
 "Wenatchee": "Pangborn Memorial Airport (EAT)",
 "Yakima": "Yakima Air Terminal (McAllister Field) (YKM)",
 "Clarksburg": "North Central West Virginia Airport (CKB)",
 "Huntington": "Tri-State Airport (Milton J. Ferguson Field) (HTS)",
 "Lewisburg": "Greenbrier Valley Airport (LWB)",
 "Morgantown": "Morgantown Municipal Airport (Walter L. Bill Hart Field) (MGW)",
 "Appleton": "Appleton International Airport (ATW)",
 "Eau Claire": "Chippewa Valley Regional Airport (EAU)",
 "Green Bay": "Austin Straubel International Airport (GRB)",
 "La Crosse": "La Crosse Regional Airport (LSE)",
 "Madison": "Dane County Regional Airport (Truax Field) (MSN)",
 "Milwaukee": "General Mitchell International Airport (MKE)",
 "Rhinelander": "Rhinelander-Oneida County Airport (RHI)",
 "Wausau": "Central Wisconsin Airport (CWA)",
 "Casper": "Casper/Natrona County International Airport (CPR)",
 "Cheyenne": "Cheyenne Regional Airport (Jerry Olson Field) (CYS)",
 "Cody": "Yellowstone Regional Airport (COD)",
 "Gillette": "Gillette-Campbell County Airport (GCC)",
 "Laramie": "Laramie Regional Airport (LAR)",
 "Riverton": "Riverton Regional Airport (RIW)",
 "Rock Springs": "Rock Springs – Sweetwater County Airport (RKS)",
 "Sheridan": "Sheridan County Airport (SHR)",
 "Pago Pago, Tutuila": "Pago Pago International Airport (PPG)",
 "Agana / Tamuning": "Antonio B. Won Pat International Airport (GUM)",
 "Obyan, Saipan Island": "Saipan International Airport (Francisco C. Ada) (GSN)",
 "Rota Island": "Rota International Airport (GRO)",
 "Aguadilla": "Rafael Hernández International Airport (BQN)",
 "Ponce": "Mercedita International Airport (PSE)",
 "San Juan / Carolina": "Luis Muñoz Marín International Airport (SJU)",
 "San Juan / Miramar": "Fernando Luis Ribas Dominicci Airport (Isla Grande Airport) (SIG)",
 "Vieques": "Antonio Rivera Rodríguez Airport (VQS)",
 "Charlotte Amalie, St. Thomas": "Cyril E. King Airport (STT)",
 "Christiansted, St. Croix": "Henry E. Rohlsen Airport (STX)"
}

var airportsByCode = {
 "BHM": "Birmingham - Birmingham–Shuttlesworth International Airport",
 "DHN": "Dothan - Dothan Regional Airport",
 "HSV": "Huntsville - Huntsville International Airport",
 "MOB": "Mobile - Mobile Regional Airport",
 "MGM": "Montgomery - Montgomery Regional Airport ",
 "IFP": "Bullhead City - Laughlin/Bullhead International Airport",
 "FLG": "Flagstaff - Flagstaff Pulliam Airport",
 "GCN": "Grand Canyon / Tusayan - Grand Canyon National Park Airport",
 "IWA": "Mesa - Phoenix–Mesa Gateway Airport",
 "PGA": "Page - Page Municipal Airport",
 "1G4": "Peach Springs - Grand Canyon West Airport",
 "PHX": "Phoenix - Phoenix Sky Harbor International Airport",
 "TUS": "Tucson - Tucson International Airport",
 "NYL": "Yuma - Yuma International Airport / MCAS Yuma",
 "XNA": "Fayetteville - Northwest Arkansas Regional Airport",
 "FSM": "Fort Smith - Fort Smith Regional Airport",
 "LIT": "Little Rock - Bill and Hillary Clinton National Airport",
 "TXK": "Texarkana - Texarkana Regional Airport",
 "ACV": "Arcata / Eureka - Arcata Airport",
 "BFL": "Bakersfield - Meadows Field",
 "BUR": "Burbank - Bob Hope Airport",
 "CRQ": "Carlsbad - McClellan–Palomar Airport",
 "CIC": "Chico - Chico Municipal Airport",
 "CEC": "Crescent City - Del Norte County Airport",
 "FAT": "Fresno - Fresno Yosemite International Airport",
 "LGB": "Long Beach - Long Beach Airport",
 "LAX": "Los Angeles - Los Angeles International Airport",
 "MMH": "Mammoth Lakes - Mammoth Yosemite Airport",
 "MOD": "Modesto - Modesto City–County Airport",
 "MRY": "Monterey - Monterey Regional Airport",
 "OAK": "Oakland - Oakland International Airport",
 "ONT": "Ontario - Ontario International Airport",
 "PSP": "Palm Springs - Palm Springs International Airport",
 "RDD": "Redding - Redding Municipal Airport",
 "SMF": "Sacramento - Sacramento International Airport",
 "SAN": "San Diego - San Diego International Airport",
 "SFO": "San Francisco - San Francisco International Airport",
 "SJC": "San Jose - Norman Y. Mineta San José International Airport",
 "SBP": "San Luis Obispo - San Luis Obispo County Regional Airport",
 "SNA": "Santa Ana - John Wayne Airport",
 "SBA": "Santa Barbara - Santa Barbara Municipal Airport",
 "SMX": "Santa Maria - Santa Maria Public Airport",
 "STS": "Santa Rosa - Charles M. Schulz–Sonoma County Airport",
 "SCK": "Stockton - Stockton Metropolitan Airport",
 "ASE": "Aspen - Aspen-Pitkin County Airport",
 "COS": "Colorado Springs - City of Colorado Springs Municipal Airport",
 "DEN": "Denver - Denver International Airport",
 "DRO": "Durango - Durango-La Plata County Airport",
 "EGE": "Eagle - Eagle County Regional Airport",
 "GJT": "Grand Junction - Grand Junction Regional Airport",
 "GUC": "Gunnison - Gunnison-Crested Butte Regional Airport",
 "HDN": "Hayden - Yampa Valley Airport",
 "MTJ": "Montrose - Montrose Regional Airport",
 "BDL": "Hartford - Bradley International Airport",
 "HVN": "New Haven - Tweed New Haven Regional Airport",
 "DAB": "Daytona Beach - Daytona Beach International Airport",
 "FLL": "Fort Lauderdale - Fort Lauderdale–Hollywood International Airport",
 "RSW": "Fort Myers - Southwest Florida International Airport",
 "GNV": "Gainesville - Gainesville Regional Airport",
 "JAX": "Jacksonville - Jacksonville International Airport",
 "EYW": "Key West - Key West International Airport",
 "MLB": "Melbourne - Melbourne International Airport",
 "MIA": "Miami - Miami International Airport",
 "MCO": "Orlando - Orlando International Airport",
 "SFB": "Orlando/Sanford - Orlando Sanford International Airport",
 "ECP": "Panama City Beach - Northwest Florida Beaches International Airport",
 "PNS": "Pensacola - Pensacola International Airport",
 "PGD": "Punta Gorda - Punta Gorda Airport",
 "SRQ": "Sarasota / Bradenton - Sarasota–Bradenton International Airport",
 "SGJ": "St. Augustine - Northeast Florida Regional Airport",
 "PIE": "St. Petersburg/Clearwater - St. Pete–Clearwater International Airport",
 "TLH": "Tallahassee - Tallahassee International Airport",
 "TPA": "Tampa - Tampa International Airport",
 "VPS": "Valparaiso - Destin–Fort Walton Beach Airport / Eglin Air Force Base",
 "PBI": "West Palm Beach - Palm Beach International Airport",
 "ABY": "Albany - Southwest Georgia Regional Airport",
 "ATL": "Atlanta - Hartsfield-Jackson Atlanta International Airport",
 "AGS": "Augusta - Augusta Regional Airport",
 "BQK": "Brunswick - Brunswick Golden Isles Airport",
 "CSG": "Columbus - Columbus Metropolitan Airport",
 "SAV": "Savannah - Savannah/Hilton Head International Airport",
 "VLD": "Valdosta - Valdosta Regional Airport",
 "ITO": "Hilo - Hilo International Airport",
 "HNL": "Honolulu - Honolulu International Airport",
 "OGG": "Kahului - Kahului Airport",
 "KOA": "Kailua/Kona - Kona International Airport at Keahole",
 "MKK": "Kaunakakai - Molokai Airport",
 "LNY": "Lanai City - Lanai Airport ",
 "LIH": "Lihue - Lihue Airport",
 "BOI": "Boise - Boise Airport",
 "SUN": "Hailey - Friedman Memorial Airport",
 "IDA": "Idaho Falls - Idaho Falls Regional Airport",
 "LWS": "Lewiston - Lewiston-Nez Perce County Airport",
 "PIH": "Pocatello / Arbon Valley - Pocatello Regional Airport",
 "TWF": "Twin Falls - Magic Valley Regional Airport",
 "BLV": "Belleville - MidAmerica St. Louis Airport / Scott Air Force Base",
 "BMI": "Bloomington / Normal - Central Illinois Regional Airport at Bloomington-Normal",
 "CMI": "Champaign / Urbana - University of Illinois - Willard Airport",
 "ORD": "Chicago - Chicago OHare International Airport",
 "MDW": "Chicago - Chicago Midway International Airport",
 "MWA": "Marion - Williamson County Regional Airport",
 "MLI": "Moline - Quad City International Airport",
 "PIA": "Peoria - General Downing - Peoria International Airport",
 "UIN": "Quincy - Quincy Regional Airport",
 "RFD": "Rockford - Chicago Rockford International Airport",
 "SPI": "Springfield - Abraham Lincoln Capital Airport",
 "EVV": "Evansville - Evansville Regional Airport",
 "FWA": "Fort Wayne - Fort Wayne International Airport",
 "IND": "Indianapolis - Indianapolis International Airport",
 "SBN": "South Bend - South Bend International Airport",
 "CID": "Cedar Rapids - The Eastern Iowa Airport",
 "DSM": "Des Moines - Des Moines International Airport",
 "DBQ": "Dubuque - Dubuque Regional Airport",
 "SUX": "Sioux City - Sioux Gateway Airport",
 "ALO": "Waterloo - Waterloo Regional Airport",
 "GCK": "Garden City - Garden City Regional Airport",
 "MHK": "Manhattan - Manhattan Regional Airport",
 "ICT": "Wichita - Wichita Dwight D. Eisenhower National Airport",
 "CVG": "Covington - Cincinnati/Northern Kentucky International Airport",
 "LEX": "Lexington - Blue Grass Airport",
 "SDF": "Louisville - Louisville International Airport",
 "OWB": "Owensboro - Owensboro-Daviess County Regional Airport",
 "PAH": "Paducah - Barkley Regional Airport",
 "AEX": "Alexandria - Alexandria International Airport",
 "BTR": "Baton Rouge - Baton Rouge Metropolitan Airport",
 "LFT": "Lafayette - Lafayette Regional Airport",
 "LCH": "Lake Charles - Lake Charles Regional Airport",
 "MLU": "Monroe - Monroe Regional Airport",
 "MSY": "New Orleans - Louis Armstrong New Orleans International Airport",
 "SHV": "Shreveport - Shreveport Regional Airport",
 "BGR": "Bangor - Bangor International Airport",
 "BHB": "Bar Harbor - Hancock County-Bar Harbor Airport",
 "PWM": "Portland - Portland International Jetport",
 "RKD": "Rockland - Knox County Regional Airport",
 "BWI": "Baltimore - Baltimore/Washington International Thurgood Marshall Airport",
 "SBY": "Salisbury - Salisbury-Ocean City Wicomico Regional Airport",
 "HGR": "Hagerstown - Hagerstown Regional Airport",
 "BOS": "Boston - Gen. Edward Lawrence Logan International Airport",
 "HYA": "Hyannis - Barnstable Municipal Airport",
 "ACK": "Nantucket - Nantucket Memorial Airport",
 "PVC": "Provincetown - Provincetown Municipal Airport",
 "MVY": "Vineyard Haven - Marthas Vineyard Airport",
 "ORH": "Worcester - Worcester Regional Airport",
 "APN": "Alpena - Alpena County Regional Airport",
 "CVX": "Charlevoix - Charlevoix Municipal Airport",
 "DTW": "Detroit / Romulus - Detroit Metropolitan Wayne County Airport",
 "ESC": "Escanaba - Delta County Airport",
 "FNT": "Flint - Bishop International Airport",
 "GRR": "Grand Rapids - Gerald R. Ford International Airport",
 "CMX": "Hancock / Calumet - Houghton County Memorial Airport",
 "IMT": "Iron Mountain / Kingsford - Ford Airport",
 "AZO": "Kalamazoo / Battle Creek - Kalamazoo/Battle Creek International Airport",
 "LAN": "Lansing - Capital Region International Airport",
 "SAW": "Marquette / Gwinn - Sawyer International Airport",
 "MKG": "Muskegon - Muskegon County Airport",
 "PLN": "Pellston - Pellston Regional Airport of Emmet County",
 "MBS": "Saginaw - MBS International Airport",
 "CIU": "Sault Ste. Marie - Chippewa County International Airport",
 "TVC": "Traverse City - Cherry Capital Airport",
 "BJI": "Bemidji - Bemidji Regional Airport",
 "BRD": "Brainerd - Brainerd Lakes Regional Airport",
 "DLH": "Duluth - Duluth International Airport",
 "HIB": "Hibbing - Range Regional Airport",
 "INL": "International Falls - Falls International Airport",
 "MSP": "Minneapolis - Minneapolis–St. Paul International Airport",
 "RST": "Rochester - Rochester International Airport",
 "STC": "St. Cloud - St. Cloud Regional Airport",
 "GTR": "Columbus / West Point / Starkville - Golden Triangle Regional Airport",
 "GPT": "Gulfport / Biloxi - Gulfport–Biloxi International Airport",
 "PIB": "Hattiesburg / Laurel - Hattiesburg–Laurel Regional Airport",
 "JAN": "Jackson - Jackson–Evers International Airport",
 "COU": "Columbia - Columbia Regional Airport",
 "JLN": "Joplin - Joplin Regional Airport",
 "MCI": "Kansas City - Kansas City International Airport",
 "SGF": "Springfield - Springfield-Branson National Airport",
 "STL": "St. Louis - Lambert-St. Louis International Airport",
 "BIL": "Billings - Billings Logan International Airport",
 "BZN": "Bozeman - Bozeman Yellowstone International Airport",
 "BTM": "Butte - Bert Mooney Airport",
 "GTF": "Great Falls - Great Falls International Airport",
 "HLN": "Helena - Helena Regional Airport",
 "GPI": "Kalispell - Glacier Park International Airport",
 "MSO": "Missoula - Missoula International Airport",
 "GRI": "Grand Island - Central Nebraska Regional Airport",
 "EAR": "Kearney - Kearney Regional Airport",
 "LNK": "Lincoln - Lincoln Airport",
 "OMA": "Omaha - Eppley Airfield",
 "BFF": "Scottsbluff - Western Nebraska Regional Airport",
 "BVU": "Boulder City - Boulder City Municipal Airport",
 "EKO": "Elko - Elko Regional Airport",
 "LAS": "Las Vegas - McCarran International Airport",
 "RNO": "Reno - Reno/Tahoe International Airport",
 "LEB": "Lebanon - Lebanon Municipal Airport",
 "MHT": "Manchester - Manchester–Boston Regional Airport",
 "ACY": "Atlantic City - Atlantic City International Airport",
 "TTN": "Trenton - Trenton Mercer Airport",
 "EWR": "Newark - Newark Liberty International Airport",
 "ABQ": "Albuquerque - Albuquerque International Sunport",
 "FMN": "Farmington - Four Corners Regional Airport",
 "HOB": "Hobbs - Lea County Regional Airport",
 "ROW": "Roswell - Roswell International Air Center",
 "SAF": "Santa Fe - Santa Fe Municipal Airport",
 "ALB": "Albany - Albany International Airport",
 "BGM": "Binghamton - Greater Binghamton Airport",
 "BUF": "Buffalo - Buffalo Niagara International Airport",
 "ELM": "Elmira / Corning - Elmira/Corning Regional Airport",
 "ISP": "Islip - Long Island MacArthur Airport",
 "ITH": "Ithaca - Ithaca Tompkins Regional Airport",
 "JFK": "New York - John F. Kennedy International Airport",
 "LGA": "New York - LaGuardia Airport",
 "SWF": "Newburgh - Stewart International Airport",
 "IAG": "Niagara Falls - Niagara Falls International Airport",
 "PBG": "Plattsburgh - Plattsburgh International Airport",
 "ROC": "Rochester - Greater Rochester International Airport",
 "SYR": "Syracuse - Syracuse Hancock International Airport",
 "ART": "Watertown - Watertown International Airport",
 "HPN": "White Plains - Westchester County Airport",
 "AVL": "Asheville - Asheville Regional Airport",
 "CLT": "Charlotte - Charlotte/Douglas International Airport",
 "FAY": "Fayetteville - Fayetteville Regional Airport",
 "GSO": "Greensboro - Piedmont Triad International Airport",
 "PGV": "Greenville - Pitt-Greenville Airport",
 "OAJ": "Jacksonville - Albert J. Ellis Airport",
 "EWN": "New Bern - Coastal Carolina Regional Airport",
 "RDU": "Raleigh - Raleigh-Durham International Airport",
 "ILM": "Wilmington - Wilmington International Airport",
 "BIS": "Bismarck - Bismarck Municipal Airport",
 "DIK": "Dickinson - Dickinson Theodore Roosevelt Regional Airport",
 "FAR": "Fargo - Hector International Airport",
 "GFK": "Grand Forks - Grand Forks International Airport",
 "MOT": "Minot - Minot International Airport",
 "ISN": "Williston - Sloulin Field International Airport",
 "CAK": "Akron / Canton - Akron-Canton Regional Airport",
 "CLE": "Cleveland - Cleveland-Hopkins International Airport",
 "CMH": "Columbus - Port Columbus International Airport",
 "LCK": "Columbus - Rickenbacker International Airport",
 "DAY": "Dayton - James M. Cox Dayton International Airport",
 "TOL": "Toledo - Toledo Express Airport",
 "YNG": "Youngstown / Warren - Youngstown-Warren Regional Airport / Youngstown ARS",
 "LAW": "Lawton - Lawton–Fort Sill Regional Airport",
 "OKC": "Oklahoma City - Will Rogers World Airport",
 "TUL": "Tulsa - Tulsa International Airport",
 "EUG": "Eugene - Eugene Airport",
 "LMT": "Klamath Falls - Klamath Falls Airport",
 "MFR": "Medford - Rogue Valley International-Medford Airport",
 "OTH": "North Bend - Southwest Oregon Regional Airport",
 "PDX": "Portland - Portland International Airport",
 "RDM": "Redmond - Redmond Municipal Airport",
 "ABE": "Allentown - Lehigh Valley International Airport",
 "ERI": "Erie - Erie International Airport",
 "MDT": "Harrisburg / Middletown - Harrisburg International Airport",
 "LBE": "Latrobe - Arnold Palmer Regional Airport",
 "PHL": "Philadelphia - Philadelphia International Airport",
 "PIT": "Pittsburgh - Pittsburgh International Airport",
 "UNV": "State College - University Park Airport",
 "AVP": "Wilkes-Barre / Scranton - Wilkes-Barre/Scranton International Airport",
 "IPT": "Williamsport - Williamsport Regional Airport",
 "PVD": "Providence / Warwick - Theodore Francis Green State Airport",
 "WST": "Westerly - Westerly State Airport",
 "CHS": "Charleston - Charleston International Airport / Charleston AFB",
 "CAE": "Columbia - Columbia Metropolitan Airport",
 "FLO": "Florence - Florence Regional Airport",
 "GSP": "Greer - Greenville-Spartanburg International Airport",
 "HXD": "Hilton Head Island - Hilton Head Airport",
 "MYR": "Myrtle Beach - Myrtle Beach International Airport",
 "ABR": "Aberdeen - Aberdeen Regional Airport",
 "PIR": "Pierre - Pierre Regional Airport",
 "RAP": "Rapid City - Rapid City Regional Airport",
 "FSD": "Sioux Falls - Sioux Falls Regional Airport",
 "TRI": "Bristol / Johnson City / Kingsport - Tri-Cities Regional Airport",
 "CHA": "Chattanooga - Chattanooga Metropolitan Airport",
 "TYS": "Knoxville - McGhee Tyson Airport",
 "MEM": "Memphis - Memphis International Airport",
 "BNA": "Nashville - Nashville International Airport",
 "ABI": "Abilene - Abilene Regional Airport",
 "AMA": "Amarillo - Rick Husband Amarillo International Airport",
 "AUS": "Austin - Austin-Bergstrom International Airport",
 "BPT": "Beaumont / Port Arthur - Jack Brooks Regional Airport",
 "BRO": "Brownsville - Brownsville/South Padre Island International Airport",
 "CLL": "College Station - Easterwood Airport",
 "CRP": "Corpus Christi / Kingsville - Corpus Christi International Airport",
 "DAL": "Dallas - Dallas Love Field",
 "DFW": "Dallas-Fort Worth - Dallas/Fort Worth International Airport",
 "DRT": "Del Rio - Del Rio International Airport",
 "ELP": "El Paso - El Paso International Airport",
 "GRK": "Fort Hood - Killeen-Fort Hood Regional Airport",
 "HRL": "Harlingen - Valley International Airport",
 "IAH": "Houston - George Bush Intercontinental Airport",
 "HOU": "Houston - William P. Hobby Airport",
 "LRD": "Laredo - Laredo International Airport",
 "GGG": "Longview - East Texas Regional Airport",
 "LBB": "Lubbock - Lubbock Preston Smith International Airport",
 "MFE": "McAllen - McAllen-Miller International Airport",
 "MAF": "Midland - Midland International Airport",
 "SJT": "San Angelo - San Angelo Regional Airport",
 "SAT": "San Antonio - San Antonio International Airport",
 "TYR": "Tyler - Tyler Pounds Regional Airport",
 "ACT": "Waco - Waco Regional Airport",
 "SPS": "Wichita Falls - Wichita Falls Municipal Airport / Sheppard Air Force Base",
 "PVU": "Provo - Provo Municipal Airport",
 "SLC": "Salt Lake City - Salt Lake City International Airport",
 "SGU": "St. George / Beaver - St. George Regional Airport",
 "ENV": "Wendover - Wendover Airport",
 "BTV": "Burlington - Burlington International Airport",
 "CHO": "Charlottesville - Charlottesville–Albemarle Airport",
 "LYH": "Lynchburg - Lynchburg Regional Airport",
 "PHF": "Newport News - Newport News/Williamsburg International Airport",
 "ORF": "Norfolk - Norfolk International Airport",
 "RIC": "Richmond - Richmond International Airport",
 "ROA": "Roanoke - Roanoke Regional Airport",
 "SHD": "Staunton / Waynesboro / Harrisonburg - Shenandoah Valley Regional Airport",
 "DCA": "Washington, D.C. / Arlington County - Ronald Reagan Washington National Airport",
 "IAD": "Washington, D.C. / Dulles / Chantilly - Washington Dulles International Airport",
 "BLI": "Bellingham - Bellingham International Airport",
 "FHR": "Friday Harbor - Friday Harbor Airport",
 "PSC": "Pasco - Tri-Cities Airport",
 "CLM": "Port Angeles - William R. Fairchild International Airport",
 "PUW": "Pullman / Moscow, Idaho - Pullman/Moscow Regional Airport",
 "BFI": "Seattle - King County International Airport",
 "SEA": "Seattle / Tacoma  - Seattle–Tacoma International Airport",
 "GEG": "Spokane - Spokane International Airport",
 "ALW": "Walla Walla - Walla Walla Regional Airport",
 "EAT": "Wenatchee - Pangborn Memorial Airport",
 "YKM": "Yakima - Yakima Air Terminal",
 "CRW": "Charleston - Yeager Airport",
 "CKB": "Clarksburg - North Central West Virginia Airport",
 "HTS": "Huntington - Tri-State Airport",
 "LWB": "Lewisburg - Greenbrier Valley Airport",
 "MGW": "Morgantown - Morgantown Municipal Airport",
 "ATW": "Appleton - Appleton International Airport",
 "EAU": "Eau Claire - Chippewa Valley Regional Airport",
 "GRB": "Green Bay - Austin Straubel International Airport",
 "LSE": "La Crosse - La Crosse Regional Airport",
 "MSN": "Madison - Dane County Regional Airport",
 "MKE": "Milwaukee - General Mitchell International Airport",
 "RHI": "Rhinelander - Rhinelander-Oneida County Airport",
 "CWA": "Wausau - Central Wisconsin Airport",
 "CPR": "Casper - Casper/Natrona County International Airport",
 "CYS": "Cheyenne - Cheyenne Regional Airport",
 "COD": "Cody - Yellowstone Regional Airport",
 "GCC": "Gillette - Gillette-Campbell County Airport",
 "JAC": "Jackson - Jackson Hole Airport",
 "LAR": "Laramie - Laramie Regional Airport",
 "RIW": "Riverton - Riverton Regional Airport",
 "RKS": "Rock Springs - Rock Springs – Sweetwater County Airport",
 "SHR": "Sheridan - Sheridan County Airport",
 "PPG": "Pago Pago, Tutuila - Pago Pago International Airport",
 "GUM": "Agana / Tamuning - Antonio B. Won Pat International Airport",
 "GSN": "Obyan, Saipan Island - Saipan International Airport",
 "GRO": "Rota Island - Rota International Airport",
 "BQN": "Aguadilla - Rafael Hernández International Airport",
 "PSE": "Ponce - Mercedita International Airport",
 "SJU": "San Juan / Carolina - Luis Muñoz Marín International Airport",
 "SIG": "San Juan / Miramar - Fernando Luis Ribas Dominicci Airport",
 "VQS": "Vieques - Antonio Rivera Rodríguez Airport",
 "STT": "Charlotte Amalie, St. Thomas - Cyril E. King Airport",
 "STX": "Christiansted, St. Croix - Henry E. Rohlsen Airport" 
}

var airportsByName = {
   "Birmingham–Shuttlesworth International Airport": "Birmingham (BHM)",
   "Dothan Regional Airport": "Dothan (DHN)",
   "Huntsville International Airport (Carl T. Jones Field)": "Huntsville (HSV)",
   "Mobile Regional Airport": "Mobile (MOB)",
   "Montgomery Regional Airport (Dannelly Field)": "Montgomery (MGM)",
   "Laughlin/Bullhead International Airport": "Bullhead City (IFP)",
   "Flagstaff Pulliam Airport": "Flagstaff (FLG)",
   "Grand Canyon National Park Airport": "Grand Canyon / Tusayan (GCN)",
   "Phoenix–Mesa Gateway Airport": "Mesa (IWA)",
   "Page Municipal Airport": "Page (PGA)",
   "Grand Canyon West Airport": "Peach Springs (1G4)",
   "Phoenix Sky Harbor International Airport": "Phoenix (PHX)",
   "Tucson International Airport": "Tucson (TUS)",
   "Yuma International Airport / MCAS Yuma": "Yuma (NYL)",
   "Northwest Arkansas Regional Airport": "Fayetteville (XNA)",
   "Fort Smith Regional Airport": "Fort Smith (FSM)",
   "Bill and Hillary Clinton National Airport (Adams Field) (was Little Rock National)": "Little Rock (LIT)",
   "Texarkana Regional Airport (Webb Field)": "Texarkana (TXK)",
   "Arcata Airport": "Arcata / Eureka (ACV)",
   "Meadows Field": "Bakersfield (BFL)",
   "Bob Hope Airport (Hollywood Burbank Airport)": "Burbank (BUR)",
   "McClellan–Palomar Airport": "Carlsbad (CRQ)",
   "Chico Municipal Airport": "Chico (CIC)",
   "Del Norte County Airport (Jack McNamara Field)": "Crescent City (CEC)",
   "Fresno Yosemite International Airport": "Fresno (FAT)",
   "Long Beach Airport (Daugherty Field)": "Long Beach (LGB)",
   "Los Angeles International Airport": "Los Angeles (LAX)",
   "Mammoth Yosemite Airport": "Mammoth Lakes (MMH)",
   "Modesto City–County Airport (Harry Sham Field)": "Modesto (MOD)",
   "Monterey Regional Airport (was Monterey Peninsula Airport)": "Monterey (MRY)",
   "Oakland International Airport": "Oakland (OAK)",
   "Ontario International Airport": "Ontario (ONT)",
   "Palm Springs International Airport": "Palm Springs (PSP)",
   "Redding Municipal Airport": "Redding (RDD)",
   "Sacramento International Airport": "Sacramento (SMF)",
   "San Diego International Airport (Lindbergh Field)": "San Diego (SAN)",
   "San Francisco International Airport": "San Francisco (SFO)",
   "San José International Airport": "San Jose (SJC)",
   "San Luis Obispo County Regional Airport (McChesney Field)": "San Luis Obispo (SBP)",
   "John Wayne Airport (was Orange County Airport)": "Santa Ana (SNA)",
   "Santa Barbara Municipal Airport (Santa Barbara Airport)": "Santa Barbara (SBA)",
   "Santa Maria Public Airport (Capt G. Allan Hancock Field)": "Santa Maria (SMX)",
   "Charles M. Schulz–Sonoma County Airport": "Santa Rosa (STS)",
   "Stockton Metropolitan Airport": "Stockton (SCK)",
   "Aspen-Pitkin County Airport (Sardy Field)": "Aspen (ASE)",
   "City of Colorado Springs Municipal Airport": "Colorado Springs (COS)",
   "Denver International Airport": "Denver (DEN)",
   "Durango-La Plata County Airport": "Durango (DRO)",
   "Eagle County Regional Airport": "Eagle (EGE)",
   "Grand Junction Regional Airport (Walker Field)": "Grand Junction (GJT)",
   "Gunnison-Crested Butte Regional Airport": "Gunnison (GUC)",
   "Yampa Valley Airport (Yampa Valley Regional)": "Hayden (HDN)",
   "Montrose Regional Airport": "Montrose (MTJ)",
   "Bradley International Airport": "Hartford (BDL)",
   "Tweed New Haven Regional Airport": "New Haven (HVN)",
   "Daytona Beach International Airport": "Daytona Beach (DAB)",
   "Fort Lauderdale–Hollywood International Airport": "Fort Lauderdale (FLL)",
   "Southwest Florida International Airport": "Fort Myers (RSW)",
   "Gainesville Regional Airport": "Gainesville (GNV)",
   "Jacksonville International Airport": "Jacksonville (JAX)",
   "Key West International Airport": "Key West (EYW)",
   "Melbourne International Airport": "Melbourne (MLB)",
   "Miami International Airport": "Miami (MIA)",
   "Orlando International Airport": "Orlando (MCO)",
   "Orlando Sanford International Airport": "Orlando/Sanford (SFB)",
   "Northwest Florida Beaches International Airport [nb 2]": "Panama City Beach (ECP)",
   "Pensacola International Airport (Pensacola Gulf Coast Regional Airport)": "Pensacola (PNS)",
   "Punta Gorda Airport (was Charlotte County Airport)": "Punta Gorda (PGD)",
   "Sarasota–Bradenton International Airport": "Sarasota / Bradenton (SRQ)",
   "Northeast Florida Regional Airport (was St. Augustine Airport)": "St. Augustine (SGJ)",
   "St. Pete–Clearwater International Airport": "St. Petersburg/Clearwater (PIE)",
   "Tallahassee International Airport": "Tallahassee (TLH)",
   "Tampa International Airport": "Tampa (TPA)",
   "Destin–Fort Walton Beach Airport / Eglin Air Force Base": "Valparaiso (VPS)",
   "Palm Beach International Airport": "West Palm Beach (PBI)",
   "Southwest Georgia Regional Airport": "Albany (ABY)",
   "Hartsfield-Jackson Atlanta International Airport": "Atlanta (ATL)",
   "Augusta Regional Airport (Bush Field)": "Augusta (AGS)",
   "Brunswick Golden Isles Airport": "Brunswick (BQK)",
   "Columbus Metropolitan Airport": "Columbus (CSG)",
   "Savannah/Hilton Head International Airport": "Savannah (SAV)",
   "Valdosta Regional Airport": "Valdosta (VLD)",
   "Hilo International Airport": "Hilo (ITO)",
   "Honolulu International Airport": "Honolulu (HNL)",
   "Kahului Airport": "Kahului (OGG)",
   "Kona International Airport at Keahole": "Kailua/Kona (KOA)",
   "Molokai Airport (Molokaʻi Airport)": "Kaunakakai (MKK)",
   "Lanai Airport (Lānaʻi Airport)": "Lanai City (Lānaʻi City) (LNY)",
   "Lihue Airport (Līhuʻe Airport)": "Lihue (Līhuʻe) (LIH)",
   "Boise Airport (Boise Air Terminal) (Gowen Field)": "Boise (BOI)",
   "Friedman Memorial Airport": "Hailey (SUN)",
   "Idaho Falls Regional Airport (Fanning Field)": "Idaho Falls (IDA)",
   "Lewiston-Nez Perce County Airport": "Lewiston (LWS)",
   "Pocatello Regional Airport": "Pocatello / Arbon Valley (PIH)",
   "Magic Valley Regional Airport (Joslin Field)": "Twin Falls (TWF)",
   "MidAmerica St. Louis Airport / Scott Air Force Base": "Belleville (BLV)",
   "Central Illinois Regional Airport at Bloomington-Normal": "Bloomington / Normal (BMI)",
   "University of Illinois - Willard Airport": "Champaign / Urbana (CMI)",
   "Chicago OHare International Airport": "Chicago (ORD)",
   "Chicago Midway International Airport": "Chicago (MDW)",
   "Williamson County Regional Airport": "Marion (MWA)",
   "Quad City International Airport": "Moline (MLI)",
   "General Downing - Peoria International Airport": "Peoria (PIA)",
   "Quincy Regional Airport (Baldwin Field)": "Quincy (UIN)",
   "Chicago Rockford International Airport": "Rockford (RFD)",
   "Abraham Lincoln Capital Airport": "Springfield (SPI)",
   "Evansville Regional Airport": "Evansville (EVV)",
   "Fort Wayne International Airport": "Fort Wayne (FWA)",
   "Indianapolis International Airport": "Indianapolis (IND)",
   "South Bend International Airport (was South Bend Regional)": "South Bend (SBN)",
   "The Eastern Iowa Airport": "Cedar Rapids (CID)",
   "Des Moines International Airport": "Des Moines (DSM)",
   "Dubuque Regional Airport": "Dubuque (DBQ)",
   "Sioux Gateway Airport (Col. Bud Day Field)": "Sioux City (SUX)",
   "Waterloo Regional Airport": "Waterloo (ALO)",
   "Garden City Regional Airport": "Garden City (GCK)",
   "Manhattan Regional Airport": "Manhattan (MHK)",
   "Wichita Dwight D. Eisenhower National Airport (formerly Wichita Mid-Continent Airport)": "Wichita (ICT)",
   "Cincinnati/Northern Kentucky International Airport": "Covington (CVG)",
   "Blue Grass Airport": "Lexington (LEX)",
   "Louisville International Airport (Standiford Field)": "Louisville (SDF)",
   "Owensboro-Daviess County Regional Airport": "Owensboro (OWB)",
   "Barkley Regional Airport": "Paducah (PAH)",
   "Alexandria International Airport": "Alexandria (AEX)",
   "Baton Rouge Metropolitan Airport (Ryan Field)": "Baton Rouge (BTR)",
   "Lafayette Regional Airport": "Lafayette (LFT)",
   "Lake Charles Regional Airport": "Lake Charles (LCH)",
   "Monroe Regional Airport": "Monroe (MLU)",
   "Louis Armstrong New Orleans International Airport": "New Orleans (MSY)",
   "Shreveport Regional Airport": "Shreveport (SHV)",
   "Bangor International Airport": "Bangor (BGR)",
   "Hancock County-Bar Harbor Airport": "Bar Harbor (BHB)",
   "Portland International Jetport": "Portland (PWM)",
   "Knox County Regional Airport": "Rockland (RKD)",
   "Baltimore/Washington International Thurgood Marshall Airport": "Baltimore (BWI)",
   "Salisbury-Ocean City Wicomico Regional Airport": "Salisbury (SBY)",
   "Hagerstown Regional Airport (Richard A. Henson Field)": "Hagerstown (HGR)",
   "Gen. Edward Lawrence Logan International Airport": "Boston (BOS)",
   "Barnstable Municipal Airport (Boardman/Polando Field)": "Hyannis (HYA)",
   "Nantucket Memorial Airport": "Nantucket (ACK)",
   "Provincetown Municipal Airport": "Provincetown (PVC)",
   "Marthas Vineyard Airport": "Vineyard Haven (MVY)",
   "Worcester Regional Airport": "Worcester (ORH)",
   "Alpena County Regional Airport": "Alpena (APN)",
   "Charlevoix Municipal Airport": "Charlevoix (CVX)",
   "Detroit Metropolitan Wayne County Airport": "Detroit / Romulus (DTW)",
   "Delta County Airport": "Escanaba (ESC)",
   "Bishop International Airport": "Flint (FNT)",
   "Gerald R. Ford International Airport": "Grand Rapids (GRR)",
   "Houghton County Memorial Airport": "Hancock / Calumet (CMX)",
   "Ford Airport": "Iron Mountain / Kingsford (IMT)",
   "Kalamazoo/Battle Creek International Airport": "Kalamazoo / Battle Creek (AZO)",
   "Capital Region International Airport (was Lansing Capital City)": "Lansing (LAN)",
   "Sawyer International Airport": "Marquette / Gwinn (SAW)",
   "Muskegon County Airport": "Muskegon (MKG)",
   "Pellston Regional Airport of Emmet County": "Pellston (PLN)",
   "MBS International Airport": "Saginaw (MBS)",
   "Chippewa County International Airport": "Sault Ste. Marie (CIU)",
   "Cherry Capital Airport": "Traverse City (TVC)",
   "Bemidji Regional Airport": "Bemidji (BJI)",
   "Brainerd Lakes Regional Airport": "Brainerd (BRD)",
   "Duluth International Airport": "Duluth (DLH)",
   "Range Regional Airport (was Chisholm–Hibbing Airport)": "Hibbing (HIB)",
   "Falls International Airport": "International Falls (INL)",
   "Minneapolis–St. Paul International Airport (Wold–Chamberlain Field)": "Minneapolis (MSP)",
   "Rochester International Airport": "Rochester (RST)",
   "St. Cloud Regional Airport": "St. Cloud (STC)",
   "Golden Triangle Regional Airport": "Columbus / West Point / Starkville (GTR)",
   "Gulfport–Biloxi International Airport": "Gulfport / Biloxi (GPT)",
   "Hattiesburg–Laurel Regional Airport": "Hattiesburg / Laurel (PIB)",
   "Jackson–Evers International Airport": "Jackson (JAN)",
   "Columbia Regional Airport": "Columbia (COU)",
   "Joplin Regional Airport": "Joplin (JLN)",
   "Kansas City International Airport (originally Mid-Contintent International Airport)": "Kansas City (MCI)",
   "Springfield-Branson National Airport": "Springfield (SGF)",
   "Lambert-St. Louis International Airport": "St. Louis (STL)",
   "Billings Logan International Airport": "Billings (BIL)",
   "Bozeman Yellowstone International Airport (was Gallatin Field Airport)": "Bozeman (BZN)",
   "Bert Mooney Airport": "Butte (BTM)",
   "Great Falls International Airport": "Great Falls (GTF)",
   "Helena Regional Airport": "Helena (HLN)",
   "Glacier Park International Airport": "Kalispell (GPI)",
   "Missoula International Airport": "Missoula (MSO)",
   "Central Nebraska Regional Airport": "Grand Island (GRI)",
   "Kearney Regional Airport (was Kearney Municipal)": "Kearney (EAR)",
   "Lincoln Airport (was Lincoln Municipal)": "Lincoln (LNK)",
   "Eppley Airfield": "Omaha (OMA)",
   "Western Nebraska Regional Airport (William B. Heilig Field)": "Scottsbluff (BFF)",
   "Boulder City Municipal Airport": "Boulder City (BVU)",
   "Elko Regional Airport (J.C. Harris Field)": "Elko (EKO)",
   "McCarran International Airport": "Las Vegas (LAS)",
   "Reno/Tahoe International Airport": "Reno (RNO)",
   "Lebanon Municipal Airport": "Lebanon (LEB)",
   "Manchester–Boston Regional Airport": "Manchester (MHT)",
   "Atlantic City International Airport": "Atlantic City (ACY)",
   "Trenton Mercer Airport": "Trenton (TTN)",
   "Newark Liberty International Airport": "Newark (EWR)",
   "Albuquerque International Sunport": "Albuquerque (ABQ)",
   "Four Corners Regional Airport": "Farmington (FMN)",
   "Lea County Regional Airport": "Hobbs (HOB)",
   "Roswell International Air Center": "Roswell (ROW)",
   "Santa Fe Municipal Airport": "Santa Fe (SAF)",
   "Albany International Airport": "Albany (ALB)",
   "Greater Binghamton Airport (Edwin A. Link Field)": "Binghamton (BGM)",
   "Buffalo Niagara International Airport": "Buffalo (BUF)",
   "Elmira/Corning Regional Airport": "Elmira / Corning (ELM)",
   "Long Island MacArthur Airport": "Islip (ISP)",
   "Ithaca Tompkins Regional Airport": "Ithaca (ITH)",
   "John F. Kennedy International Airport (was New York International Airport)": "New York (JFK)",
   "LaGuardia Airport": "New York (LGA)",
   "Stewart International Airport": "Newburgh (SWF)",
   "Niagara Falls International Airport": "Niagara Falls (IAG)",
   "Plattsburgh International Airport": "Plattsburgh (PBG)",
   "Greater Rochester International Airport": "Rochester (ROC)",
   "Syracuse Hancock International Airport": "Syracuse (SYR)",
   "Watertown International Airport": "Watertown (ART)",
   "Westchester County Airport": "White Plains (HPN)",
   "Asheville Regional Airport": "Asheville (AVL)",
   "Charlotte/Douglas International Airport": "Charlotte (CLT)",
   "Fayetteville Regional Airport (Grannis Field)": "Fayetteville (FAY)",
   "Piedmont Triad International Airport": "Greensboro (GSO)",
   "Pitt-Greenville Airport": "Greenville (PGV)",
   "Albert J. Ellis Airport": "Jacksonville (OAJ)",
   "Coastal Carolina Regional Airport (was Craven County Regional)": "New Bern (EWN)",
   "Raleigh-Durham International Airport": "Raleigh (RDU)",
   "Wilmington International Airport": "Wilmington (ILM)",
   "Bismarck Municipal Airport": "Bismarck (BIS)",
   "Dickinson Theodore Roosevelt Regional Airport": "Dickinson (DIK)",
   "Hector International Airport": "Fargo (FAR)",
   "Grand Forks International Airport": "Grand Forks (GFK)",
   "Minot International Airport": "Minot (MOT)",
   "Sloulin Field International Airport": "Williston (ISN)",
   "Akron-Canton Regional Airport": "Akron / Canton (CAK)",
   "Cleveland-Hopkins International Airport": "Cleveland (CLE)",
   "Port Columbus International Airport": "Columbus (CMH)",
   "Rickenbacker International Airport": "Columbus (LCK)",
   "James M. Cox Dayton International Airport": "Dayton (DAY)",
   "Toledo Express Airport": "Toledo (TOL)",
   "Youngstown-Warren Regional Airport / Youngstown ARS": "Youngstown / Warren (YNG)",
   "Lawton–Fort Sill Regional Airport": "Lawton (LAW)",
   "Will Rogers World Airport": "Oklahoma City (OKC)",
   "Tulsa International Airport": "Tulsa (TUL)",
   "Eugene Airport (Mahlon Sweet Field)": "Eugene (EUG)",
   "Klamath Falls Airport (Kingsley Field)": "Klamath Falls (LMT)",
   "Rogue Valley International-Medford Airport": "Medford (MFR)",
   "Southwest Oregon Regional Airport": "North Bend (OTH)",
   "Portland International Airport": "Portland (PDX)",
   "Redmond Municipal Airport (Roberts Field)": "Redmond (RDM)",
   "Lehigh Valley International Airport": "Allentown (ABE)",
   "Erie International Airport (Tom Ridge Field)": "Erie (ERI)",
   "Harrisburg International Airport": "Harrisburg / Middletown (MDT)",
   "Arnold Palmer Regional Airport": "Latrobe (LBE)",
   "Philadelphia International Airport": "Philadelphia (PHL)",
   "Pittsburgh International Airport": "Pittsburgh (PIT)",
   "University Park Airport": "State College (UNV)",
   "Wilkes-Barre/Scranton International Airport": "Wilkes-Barre / Scranton (AVP)",
   "Williamsport Regional Airport": "Williamsport (IPT)",
   "Theodore Francis Green State Airport": "Providence / Warwick (PVD)",
   "Westerly State Airport": "Westerly (WST)",
   "Charleston International Airport / Charleston AFB": "Charleston (CHS)",
   "Columbia Metropolitan Airport": "Columbia (CAE)",
   "Florence Regional Airport": "Florence (FLO)",
   "Greenville-Spartanburg International Airport (Roger Milliken Field)": "Greer (GSP)",
   "Hilton Head Airport": "Hilton Head Island (HXD)",
   "Myrtle Beach International Airport": "Myrtle Beach (MYR)",
   "Aberdeen Regional Airport": "Aberdeen (ABR)",
   "Pierre Regional Airport": "Pierre (PIR)",
   "Rapid City Regional Airport": "Rapid City (RAP)",
   "Sioux Falls Regional Airport (Joe Foss Field)": "Sioux Falls (FSD)",
   "Tri-Cities Regional Airport (Tri-Cities Regional TN/VA)": "Bristol / Johnson City / Kingsport (TRI)",
   "Chattanooga Metropolitan Airport (Lovell Field)": "Chattanooga (CHA)",
   "McGhee Tyson Airport": "Knoxville (TYS)",
   "Memphis International Airport": "Memphis (MEM)",
   "Nashville International Airport (Berry Field)": "Nashville (BNA)",
   "Abilene Regional Airport": "Abilene (ABI)",
   "Rick Husband Amarillo International Airport": "Amarillo (AMA)",
   "Austin-Bergstrom International Airport": "Austin (AUS)",
   "Jack Brooks Regional Airport (was Southeast Texas Regional)": "Beaumont / Port Arthur (BPT)",
   "Brownsville/South Padre Island International Airport": "Brownsville (BRO)",
   "Easterwood Airport (Easterwood Field)": "College Station (CLL)",
   "Corpus Christi International Airport": "Corpus Christi / Kingsville (CRP)",
   "Dallas Love Field": "Dallas (DAL)",
   "Dallas/Fort Worth International Airport": "Dallas-Fort Worth (DFW)",
   "Del Rio International Airport": "Del Rio (DRT)",
   "El Paso International Airport": "El Paso (ELP)",
   "Killeen-Fort Hood Regional Airport / Robert Gray Army Airfield": "Fort Hood / Killeen / Temple (GRK)",
   "Valley International Airport": "Harlingen (HRL)",
   "George Bush Intercontinental Airport": "Houston (IAH)",
   "William P. Hobby Airport": "Houston (HOU)",
   "Laredo International Airport": "Laredo (LRD)",
   "East Texas Regional Airport": "Longview (GGG)",
   "Lubbock Preston Smith International Airport": "Lubbock (LBB)",
   "McAllen-Miller International Airport (McAllen Miller International)": "McAllen (MFE)",
   "Midland International Airport": "Midland (MAF)",
   "San Angelo Regional Airport (Mathis Field)": "San Angelo (SJT)",
   "San Antonio International Airport": "San Antonio (SAT)",
   "Tyler Pounds Regional Airport": "Tyler (TYR)",
   "Waco Regional Airport": "Waco (ACT)",
   "Wichita Falls Municipal Airport / Sheppard Air Force Base": "Wichita Falls (SPS)",
   "Provo Municipal Airport (14,858 enplanements in 2011)[1]": "Provo (PVU)",
   "Salt Lake City International Airport": "Salt Lake City (SLC)",
   "St. George Regional Airport (opened 2011)": "St. George / Beaver (SGU)",
   "Wendover Airport (charter flights)": "Wendover (ENV)",
   "Burlington International Airport": "Burlington (BTV)",
   "Charlottesville–Albemarle Airport": "Charlottesville (CHO)",
   "Lynchburg Regional Airport (Preston Glenn Field)": "Lynchburg (LYH)",
   "Newport News/Williamsburg International Airport": "Newport News (PHF)",
   "Norfolk International Airport": "Norfolk (ORF)",
   "Richmond International Airport (Byrd Field)": "Richmond (RIC)",
   "Roanoke Regional Airport (Woodrum Field)": "Roanoke (ROA)",
   "Shenandoah Valley Regional Airport": "Staunton / Waynesboro / Harrisonburg (SHD)",
   "Ronald Reagan Washington National Airport": "Washington, D.C. / Arlington County (DCA)",
   "Washington Dulles International Airport": "Washington, D.C. / Dulles / Chantilly (IAD)",
   "Bellingham International Airport": "Bellingham (BLI)",
   "Friday Harbor Airport": "Friday Harbor (FHR)",
   "Tri-Cities Airport": "Pasco (PSC)",
   "William R. Fairchild International Airport": "Port Angeles (CLM)",
   "Pullman/Moscow Regional Airport": "Pullman / Moscow, Idaho (PUW)",
   "King County International Airport (Boeing Field)": "Seattle (BFI)",
   "Seattle–Tacoma International Airport": "Seattle / Tacoma (SeaTac) (SEA)",
   "Spokane International Airport (Geiger Field)": "Spokane (GEG)",
   "Walla Walla Regional Airport": "Walla Walla (ALW)",
   "Pangborn Memorial Airport": "Wenatchee (EAT)",
   "Yakima Air Terminal (McAllister Field)": "Yakima (YKM)",
   "Yeager Airport": "Charleston (CRW)",
   "North Central West Virginia Airport (was Harrison-Marion Regional)": "Clarksburg (CKB)",
   "Tri-State Airport (Milton J. Ferguson Field)": "Huntington (HTS)",
   "Greenbrier Valley Airport": "Lewisburg (LWB)",
   "Morgantown Municipal Airport (Walter L. Bill Hart Field)": "Morgantown (MGW)",
   "Appleton International Airport": "Appleton (ATW)",
   "Chippewa Valley Regional Airport": "Eau Claire (EAU)",
   "Austin Straubel International Airport": "Green Bay (GRB)",
   "La Crosse Regional Airport": "La Crosse (LSE)",
   "Dane County Regional Airport (Truax Field)": "Madison (MSN)",
   "General Mitchell International Airport": "Milwaukee (MKE)",
   "Rhinelander-Oneida County Airport": "Rhinelander (RHI)",
   "Central Wisconsin Airport": "Wausau (CWA)",
   "Casper/Natrona County International Airport": "Casper (CPR)",
   "Cheyenne Regional Airport (Jerry Olson Field)": "Cheyenne (CYS)",
   "Yellowstone Regional Airport": "Cody (COD)",
   "Gillette-Campbell County Airport": "Gillette (GCC)",
   "Jackson Hole Airport": "Jackson (JAC)",
   "Laramie Regional Airport": "Laramie (LAR)",
   "Riverton Regional Airport": "Riverton (RIW)",
   "Rock Springs – Sweetwater County Airport": "Rock Springs (RKS)",
   "Sheridan County Airport": "Sheridan (SHR)",
   "Pago Pago International Airport": "Pago Pago, Tutuila (PPG)",
   "Antonio B. Won Pat International Airport": "Agana / Tamuning (GUM)",
   "Saipan International Airport (Francisco C. Ada)": "Obyan, Saipan Island (GSN)",
   "Rota International Airport": "Rota Island (GRO)",
   "Rafael Hernández International Airport": "Aguadilla (BQN)",
   "Mercedita International Airport": "Ponce (PSE)",
   "Luis Muñoz Marín International Airport": "San Juan / Carolina (SJU)",
   "Fernando Luis Ribas Dominicci Airport (Isla Grande Airport)": "San Juan / Miramar (SIG)",
   "Antonio Rivera Rodríguez Airport": "Vieques (VQS)",
   "Cyril E. King Airport": "Charlotte Amalie, St. Thomas (STT)",
   "Henry E. Rohlsen Airport": "Christiansted, St. Croix (STX)"
}



// https://en.wikipedia.org/wiki/List_of_airports_in_the_United_States
// I USED THE BELOW REFERENCES TO BUILD OUT THE BELOW METHODS
// 1) http://ruby.bastardsbook.com/chapters/web-crawling/
// 2) https://www.sitepoint.com/nokogiri-fundamentals-extract-html-web/
// 3) http://stackoverflow.com/questions/5376576/ruby-nokogiri-xpath-get-content-of-node
// 4) https://github.com/sparklemotion/nokogiri


// require 'nokogiri'
// require 'open-uri'
// require 'pry'

// def noko
//   page = Nokogiri::HTML(open("https://en.wikipedia.org/wiki/List_of_airports_in_the_United_States"))
//   @rows = page.css('div#mw-content-text.mw-content-ltr table.wikitable.sortable tr')
// end 

// def airports
//   @airports
// end


// def airport_builder_by_city
//   @airports = {}
//   noko.each do |row|
//     if !row.children[1].children.first.attributes["title"].nil?
//       airports[(row.content.split("\n")[1])] = (row.content.split("\n")[5] + " " + "(" + (row.content.split("\n")[2]) + ")" )
//     end
//   end
//   airports
// end

// def airport_builder_by_code
//   @airports = {}
//   noko.each do |row|
//     if !row.children[1].children.first.attributes["title"].nil?
//       airports[(row.content.split("\n")[2])] =  ((row.content.split("\n")[1]) + " - " + (row.content.split("\n")[5]) )
//     end
//   end
//   airports
// end

// def airport_builder_by_name
//   @airports = {}
//   noko.each do |row|
//     if !row.children[1].children.first.attributes["title"].nil?
//       airports[(row.content.split("\n")[5])] = ((row.content.split("\n")[1]) + " (" + (row.content.split("\n")[2]) + ")")
//     end
//   end
//   airports
// end


// check if not nil rows[2].children[1].children.first.attributes["title"].nil?
// if not nil then do --> 
// CITY AND STATE: rows[2].children[1].children.first.attributes["title"].content
// JUST CITY: rows[2].children[1].children.first.content
// AIRPORT INITIALS: rows[2].children[3].content
// AIRPORT NAME: rows[2].children[9].content


// OR can use rows[2].content.split("\n") to get an array of the information
// BUILDING OUT HASH 
// airports = {}
// example not using iteration:
// airports[(rows[2].content.split("\n")[1])] = (rows[2].content.split("\n")[5] + " " + "(" + (rows[2].content.split("\n")[2]) + ")" )
// airports[(row.content.split("\n")[1])] = (row.content.split("\n")[5] + " " + "(" + (row.content.split("\n")[2]) + ")" )


